version: 1.0.0
shell: bash
groups:
  clean:
    env-file: .env
    tasks:
      all:
        help: Remove build artifacts, compiled files, and cache
        run: |
          rm -f .coverage
          rm -fr build/
          rm -fr dist/
          rm -fr .eggs/
          rm -fr htmlcov/
          rm -fr .pytest_cache
          rm -fr .ruff_cache
          rm -fr .mypy_cache
          find . -name '*.egg-info' -exec rm -fr {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name '__pycache__' -exec rm -fr {} +
          find . -name '*~' -exec rm -f {} +

  docs:
    help: Commands for building and previewing the documentation
    tasks:
      build:
        help: Build the documentation
        run: mkdocs build --config-file mkdocs.yaml

      preview:
        help: Preview the documentation
        dependencies:
          - task: docs.build
        run: mkdocs serve --watch docs --config-file mkdocs.yaml

  package:
    help: helper commands for handling the package
    tasks:
      build:
        help: Build the project
        run: poetry build

  tests:
    help: Test commands
    tasks:
      linter:
        help: Run lint checks
        run: |
          pre-commit install
          pre-commit run --all-files --verbose

      unit:
        help: Run tests
        args:
          params:
            help: Extra parameters for pytest
            type: str
            default: "-vv"
        run: pytest -s ${{ args.params }} tests

      smoke-1:
        help: Run smoke tests for group 1
        dependencies:
          - task: docker.killall
        vars:
          SUGAR_FLAGS: --verbose --group group1
        run: |
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose build --all
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose build --services service1-1
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --all
          sugar ${{ vars.SUGAR_FLAGS }} compose pull
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --services service1-1
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext start --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext restart --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose exec --service service1-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose stop --all
          sugar ${{ vars.SUGAR_FLAGS }} compose run --service service1-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose down

      smoke-2:
        help: Run smoke tests for group 2
        dependencies:
          - task: docker.killall
        vars:
          SUGAR_FLAGS: --verbose --group group2
        run: |
          sugar ${{ vars.SUGAR_FLAGS }} compose build --all
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose build --services service2-1
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --all
          sugar ${{ vars.SUGAR_FLAGS }} compose pull
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --services service2-1
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext start --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext restart --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose exec --service service2-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose stop --all
          sugar ${{ vars.SUGAR_FLAGS }} compose run --service service2-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose down
      smoke-services:
        help:
        dependencies:
          - task: docker.killall
        run: |
          sugar --verbose --config-file tests/containers/.services.sugar.yaml compose build

      smoke-mix:
        help: Run smoke tests for group mix
        dependencies:
          - task: docker.killall
        vars:
          SUGAR_FLAGS: --verbose --group group-mix
        run: |
          sugar ${{ vars.SUGAR_FLAGS }} compose build --all
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose build --services service1-1,service2-1
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --all
          sugar ${{ vars.SUGAR_FLAGS }} compose pull
          sugar ${{ vars.SUGAR_FLAGS }} compose pull --services service1-1,service2-1
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext start --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext restart --all --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose exec --service service2-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose stop --all
          sugar ${{ vars.SUGAR_FLAGS }} compose run --service service2-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose down

      smoke-main:
        help: Run smoke tests for group main
        dependencies:
          - task: docker.killall
        vars:
          SUGAR_FLAGS: --verbose --group group1
        run: |
          # general tests main profile/plugins
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose config
          sugar ${{ vars.SUGAR_FLAGS }} compose create
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext start --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext restart --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose exec --service service1-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose images
          sugar ${{ vars.SUGAR_FLAGS }} compose logs
          # port is not complete supported
          # sugar --verbose compose port --service service1-1
          sugar ${{ vars.SUGAR_FLAGS }} compose ps
          sugar ${{ vars.SUGAR_FLAGS }} compose pull
          sugar ${{ vars.SUGAR_FLAGS }} compose push
          sugar ${{ vars.SUGAR_FLAGS }} compose run --service service1-1 --options -T --cmd env
          sugar ${{ vars.SUGAR_FLAGS }} compose top
          sugar ${{ vars.SUGAR_FLAGS }} compose up --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose version --verbose
          # port is not complete supported
          # sugar ${{ vars.SUGAR_FLAGS }} compose events --service service1-1 --options --json --dry-run

      smoke-defaults:
        help: Run smoke tests for group defaults
        dependencies:
          - task: docker.killall
        vars:
          SUGAR_FLAGS: --verbose --group group-defaults
        run: |
          export SUGAR_PROJECT_NAME="test-`python -c 'from uuid import uuid4; print(uuid4().hex[:7])'`"
          echo $SUGAR_PROJECT_NAME
          sugar ${{ vars.SUGAR_FLAGS }} compose build
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext start --options -d
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext restart --options -d
          docker ps|grep $SUGAR_PROJECT_NAME
          sugar ${{ vars.SUGAR_FLAGS }} compose-ext stop

      smoke-final:
        help: Run final smoke tests
        dependencies:
          - task: docker.killall
        run: |
          sugar --verbose --group group-defaults compose-ext restart --options -d
          sugar --verbose --group group1 compose pause
          sugar --verbose --group group1 compose unpause
          sugar --verbose --group group1 compose kill
          sugar --verbose --group group1 compose stop
          sugar --verbose --group group1 compose rm --options --force
          sugar --verbose --group group1 compose down

      smoke-experimental:
        help: Run simple text for experimental commands
        dependencies:
          - task: docker.killall
        run: |
          sugar --verbose compose attach--help
          sugar --verbose compose cp --help
          sugar --verbose compose ls --help
          sugar --verbose compose scale --help
          sugar --verbose compose wait --help
          sugar --verbose compose watch --help

      smoke:
        help: Run final smoke tests
        dependencies:
          - task: docker.killall
          - task: tests.smoke-1
          - task: tests.smoke-2
          - task: tests.smoke-mix
          - task: tests.smoke-main
          - task: tests.smoke-defaults
          - task: tests.smoke-final
          - task: tests.smoke-services
          - task: tests.smoke-experimental
        run: |
          sugar --verbose compose --help
          sugar --verbose compose version

  docker:
    help: Commands for docker
    tasks:
      killall:
        help: Kill all running Docker containers
        run: docker kill `docker ps -q` || true

  release:
    vars:
      app: |
        npx --yes \
        -p semantic-release \
        -p conventional-changelog-conventionalcommits@7.0.2 \
        -p "@semantic-release/commit-analyzer" \
        -p "@semantic-release/release-notes-generator" \
        -p "@semantic-release/changelog" \
        -p "@semantic-release/exec" \
        -p "@semantic-release/github" \
        -p "@semantic-release/git" \
        -p "semantic-release-replace-plugin" \
        semantic-release
    tasks:
      ci:
        help: Run semantic-release on CI
        run: |
          ${{ vars.app }} --ci

      dry:
        help: Run semantic-release on CI
        run: |
          ${{ vars.app }} --dry-run
