backend: compose
env-file: .env
defaults:
  profile: "${{ env.SUGAR_profile }}"
  project-name: "sugar-${{ env.SUGAR_PROJECT_NAME }}"
profiles:
  profile1:
    project-name: project1
    config-path: tests/containers/profile1/compose.yaml
    env-file: .env
    services:
      default: service1-1,service1-3
      available:
        - name: service1-1
        - name: service1-2
        - name: service1-3

  profile2:
    config-path: tests/containers/profile2/compose.yaml
    env-file: .env
    services:
      available:
        - name: service2-1
        - name: service2-2

  profile-mix:
    config-path:
      - tests/containers/profile1/compose.yaml
      - tests/containers/profile2/compose.yaml
    env-file: .env
    services:
      available:
        - name: service1-1
        - name: service1-2
        - name: service2-1
        - name: service2-2

  profile-defaults:
    config-path:
      - tests/containers/profile1/compose.yaml
    env-file: .env
    services:
      available:
        - name: service1-1
        - name: service1-2
