backend: compose
env-file: .env
defaults:
  group: "${{ env.SUGAR_GROUP }}"
  project-name: "sugar-${{ env.SUGAR_PROJECT_NAME }}"
groups:
  group1:
    project-name: project1
    config-path: tests/containers/group1/compose.yaml
    env-file: .env
    services:
      default: service1-1,service1-3
      available:
        - name: service1-1
        - name: service1-2
        - name: service1-3

  group2:
    config-path: tests/containers/group2/compose.yaml
    env-file: .env
    services:
      available:
        - name: service2-1
        - name: service2-2

  group-mix:
    config-path:
      - tests/containers/group1/compose.yaml
      - tests/containers/group2/compose.yaml
    env-file: .env
    services:
      available:
        - name: service1-1
        - name: service1-2
        - name: service2-1
        - name: service2-2

  group-defaults:
    config-path:
      - tests/containers/group1/compose.yaml
    env-file: .env
    services:
      available:
        - name: service1-1
        - name: service1-2
